orgapp/urls.py
from django.urls import path
from .views import *


app_name = "orgapp"

urlpatterns = [
    # Admin Urls
    path('signin/', SigninView.as_view(), name="signin"),
    path('signout/', SignoutView.as_view(), name="signout"),
    path('admin/organization/', AdminOrganizationView.as_view(),
         name="adminorganization"),
    path('admin/organization/<int:pk>/edit/',
         AdminOrganizationUpdateView.as_view(), name="adminorganizationupdate"),
    path('admin/member/list/', AdminMemberListView.as_view(), name="adminmemberlist"),
    path('admin/member/create/', AdminMemberCreateView.as_view(),
         name="adminmembercreate"),
    path('admin/member/<int:pk>/edit/',
         AdminMemberUpdateView.as_view(), name="adminmemberupdate"),
    path('admin/member/<int:pk>/delete/',
         AdminMemberDeleteView.as_view(), name="adminmemberdelete"),
    path('admin/slider/list/', AdminSliderListView.as_view(), name='adminsliderlist'),
    path('admin/slider/create/', AdminSliderCreateView.as_view(),
         name='adminslidercreate'),
    path('admin/slider/<int:pk>/edit/',
         AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    path('admin/slider/<int:pk>/delete/',
         AdminSliderDeleteView.as_view(), name='adminsliderdelete'),
    path('admin/publication/list/', AdminPublicationListView.as_view(),
         name='adminpublicationlist'),
    path('admin/publication/create/', AdminPublicationCreateView.as_view(),
         name='adminpublicationcreate'),
    path('admin/publication/<int:pk>/edit/',
         AdminPublicationUpdateView.as_view(), name='adminpublicationupdate'),
    path('admin/publication/<int:pk>/delete/',
         AdminPublicationDeleteView.as_view(), name='adminpublicationdelete'),
    path('admin/contact/list/', AdminContactListView.as_view(),
         name='admincontactlist'),
    path('admin/download/list/', AdminDownloadListView.as_view(),
         name='admindownloadlist'),
    path('admin/download/create/', AdminDownloadCreateView.as_view(),
         name='admindownloadcreate'),
    path('admin/download/<int:pk>/edit/',
         AdminDownloadUpdateView.as_view(), name='admindownloadupdate'),
    path('admin/download/<int:pk>/delete/',
         AdminDownloadDeleteView.as_view(), name='admindownloaddelete'),
    path('admin/album/list/', AdminAlbumListView.as_view(), name='adminalbumlist'),
    path('admin/album/create/', AdminAlbumCreateView.as_view(),
         name='adminalbumcreate'),
    path('admin/album/<int:pk>/edit/',
         AdminAlbumUpdateView.as_view(), name='adminalbumupdate'),
    path('admin/album/<int:pk>/delete/',
         AdminAlbumDeleteView.as_view(), name='adminalbumdelete'),
    path('admin/image/list/', AdminImageListView.as_view(), name='adminimagelist'),
    path('admin/image/create/', AdminImageCreateView.as_view(),
         name='adminimagecreate'),
    path('admin/image/<int:pk>/edit/',
         AdminImageUpdateView.as_view(), name='adminimageupdate'),
    path('admin/image/<int:pk>/delete/',
         AdminImageDeleteView.as_view(), name='adminimagedelete'),
    path('admin/article/list/', AdminArticleListView.as_view(),
         name='adminarticlelist'),
    path('admin/article/create/', AdminArticleCreateView.as_view(),
         name='adminarticlecreate'),
    path('admin/article/<int:pk>/edit/',
         AdminArticleUpdateView.as_view(), name='adminarticleupdate'),
    path('admin/article/<int:pk>/delete/',
         AdminArticleDeleteView.as_view(), name='adminarticledelete'),
    path('admin/event/list/', AdminEventListView.as_view(), name='admineventlist'),
    path('admin/event/create/', AdminEventCreateView.as_view(),
         name='admineventcreate'),
    path('admin/event/<int:pk>/edit/',
         AdminEventUpdateView.as_view(), name='admineventupdate'),
    path('admin/event/<int:pk>/delete/',
         AdminEventDeleteView.as_view(), name='admineventdelete'),
    path('admin/password/change', AdminPasswordChangeView.as_view(), name= "passwordchanged"),










    # client urls
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', ContactCreateView.as_view(), name="contact"),
    path('event/list/', EventListView.as_view(), name="eventlist"),
    path('event/<int:pk>/detail/', EventDetailView.as_view(), name="eventdetail"),
    path('album/', AlbumView.as_view(), name="albumlist"),
    path('album/detail/<int:pk>/', AlbumDetailView.as_view(), name="albumdetail"),
    path('member/', MemberView.as_view(), name="memberlist"),
    path('article/', ArticleView.as_view(), name="articlelist"),
    path('article/<int:pk>/detail/',
         ArticleDetailView.as_view(), name="articledetail"),
    path("subscriber/", SubscriberCreateView.as_view(), name="subscriber"),
    path("publication/", PublicationView.as_view(), name="publication"),
    path("publication/<int:pk>/detail/", PublicationDetailView.as_view(), name="publicationdetail"),
    path("download/", DownloadView.as_view(), name="download"),
















]

orgproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('orgapp.urls')),
    path('summernote/', include('django_summernote.urls')),
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/about.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block about %}active{% endblock %}







{% block content %}

 			<section class="page-title-area" style='background:rgba(0, 0, 0, 0) url("/static/clientstatic/img/about/page-banner.jpg") repeat scroll 0 0 / cover ;'>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title text-center">
                                <h1>About us</h1>
                            </div>
                            <div class="breadcumb-area  text-center">
                                <ol class="breadcrumb">
                                    <li><a href="{% url 'orgapp:home' %}">Home</a></li>
                                    <li class="active">About us</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End page title -->
            <!-- Start about content area -->
            <section class="about-content-area pt-90 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="about-content">
                                <!-- Start section title -->
                                <div class="section-title text-center">
                                    <h2>About <span>Us</span></h2>
                                    <img src="{% static 'clientstatic/img/title-bottom.png' %}" alt="">
                                </div>
                                <!-- End section title -->
                                <p>{{orgn.about_us|safe}} </p>
                                <p></p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="about-image">
                                <img src="{{orgn.profile_image.url}}" alt="">
                                <br>
                                <br>
                                <br>
                                <br>
                                <h3>Latest Articles</h3>
                                  <div class="card" style="width: 18rem;">
                                    {% for article in articles|slice:5 %}
<!--                                       <img src="{{article.image.url}}" class="card-img-top" alt="...">
 -->                                      <div class="card-body">
                                        <h5 class="card-title">{{article.title}}</h5>
                                        <p class="card-text">{{article.content|truncatechars:200}} <a href="{% url 'orgapp:articledetail' article.pk %}">Read More</a></p>
                                      </div>
                                      {% endfor %}
                                    </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>


       </div>
                        <!-- End brand logo -->
        </div>
       </div>
            </section>






{% endblock %}

templates/clienttemplates/album.html
{% extends 'clienttemplates/clientbase.html '%}
{% load static %}
{% block album %}active{% endblock %}




{% block content %}


 
        	<!-- Start page title -->
            <section class="page-title-area" style='background:rgba(0, 0, 0, 0) url("/static/clientstatic/img/about/page-banner.jpg") repeat scroll 0 0 / cover ;'>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title text-center">
                                <h1> Our Gallery</h1>
                            </div>
                            <div class="breadcumb-area  text-center">
                                <ol class="breadcrumb">
                                    <li><a href="{% url 'orgapp:home' %}">Home</a></li>
                                    <li class="active">Album</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
         

           <section class="our-gallery pt-90 pb-60">
                <div class="container">
                    <div class="row">
                        <!-- Start section title -->
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>OUR <a href="{% url 'orgapp:albumlist' %}"><span>Album</span></a></h2>
                                <img src="img/title-bottom.png" alt="">
                             <!--    <p>We create events aiming to pear to the voice for children and gather for support. <br>Please update with our events and confirm you presence.</p> -->
                            </div>
                        </div>
                        <!-- End section title -->
                        <div class="gallery-area">
                          
                            <div id="gallery-filter">
                                <!-- Start single gallery -->
                                {% for album in albumlist %}
                                <div class="col-sm-3 mb-30 single-gallery mix all Charity Wildlife ">
                                    <div class="gallery-image-and-text">
                                        <a class=" text-center" href="{% url 'orgapp:albumdetail' album.id %}">
                                        <img class="img-responsive" src="{{album.image_set.first.image.url}}" alt=""  style="height: 200px;" />
                                            <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                                            <p>{{album.title}}</p>
                                        </a>
                                    </div>
                                </div>

                            {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </section>










{% endblock %}

templates/clienttemplates/albumdetail.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}

   	<!-- Start page title -->
            <section class="page-title-area" style='background:rgba(0, 0, 0, 0) url("/static/clientstatic/img/about/page-banner.jpg") repeat scroll 0 0 / cover ;'>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title text-center">
                                <h1>{{album.title}}</h1>
                            </div>
                            <div class="breadcumb-area  text-center">
                                <ol class="breadcrumb">
                                    <li><a href="{% url 'orgapp:home' %}">Home</a></li>
                                    <li class="active">{{album.title}}</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


              <section class="our-gallery pt-90 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>OUR <span>{{album.title}}</span></h2>
                                <img src="img/title-bottom.png" alt="">
                            </div>
                        </div>

                             <div id="gallery-filter">
							{% for alb in album.image_set.all %}
                            
                                <div class="col-sm-3 mb-30 single-gallery mix all Charity Wildlife ">
									<div class="gallery-image-and-text">
										<img class="img-responsive" src="{{alb.image.url}}" alt="" />
										<a class="image-link text-center" href="{{alb.image.url}}">
											<i class="fa fa-plus-square-o" aria-hidden="true"></i>
											<p>{{alb.album}}</p>
										</a>
									</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </section>





{% endblock %}

templates/clienttemplates/article.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block article %}active{% endblock %}


{% block content %}


       <section class="page-title-area" style='background:rgba(0, 0, 0, 0) url("/static/clientstatic/img/about/page-banner.jpg") repeat scroll 0 0 / cover ;'>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title text-center">
                                <h1>Our Article</h1>
                            </div>
                            <div class="breadcumb-area  text-center">
                                <ol class="breadcrumb">
                                    <li><a href="{% url 'orgapp:home' %}">Home</a></li>
                                    <li class="active">Article</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End page title -->
            <!-- Start our blog area -->
            <section class="our-blog-area pt-90 pb-60">
                <div class="container">
                    <div class="row">
                    	{% for article in articlelist %}
                        <!-- Start blog -->
                        <div class="blog">
                            <!-- Start single blog -->
                            <div class="col-sm-4">
                                <div class="single-blog mb-30">
                                    <div class="blo-image-and-date">
                                        <img src="{{article.image.url}}" alt="" style="height:150px">
                                    </div>
                              
                                    <div class="blog-text">
                                        <h3><a href="#">{{article.title}}</a></h3>
                                        <p>{{article.content|truncatechars:30}}</p>
                                        <a href="{% url 'orgapp:articledetail' article.pk %}">Read More...</a>
                                    </div>
                                </div>
                            </div>



                            <!-- End single blog -->
                        </div>
                        <!-- End blog -->
                 
                        {% endfor %}
                    </div>
                </div>
            </section>
















{% endblock %}

templates/clienttemplates/eventlist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block event %}active{% endblock %}




{% block content %}



   <!-- Start page title -->
            <section class="page-title-area" style='background:rgba(0, 0, 0, 0) url("/static/clientstatic/img/about/page-banner.jpg") repeat scroll 0 0 / cover ;'>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title text-center">
                                <h1>OUR EVENTS</h1>
                            </div>
                            <div class="breadcumb-area  text-center">
                                <ol class="breadcrumb">
                                    <li><a href="{% url 'orgapp:home' %}">Home</a></li>
                                    <li class="active">OUR EVENTS</li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End page title -->
            <!-- Start up comming area -->
            <section class="up-comming-area  pt-90 pb-60">
                <div class="container">
                    <div class="row">
                      {% for event in eventlist %}
                        <div class="col-sm-12">
                            <div class="up-comming-events">
                                <!-- Start single event -->
                                <div class="single-event mb-90 row">
                                    <div class="col-sm-5">
                                        <div class="event-image">
                                            <img src="{{event.image.url}}" alt="">
                                    
                                        </div>
                                    </div>
                                    <div class="col-sm-7">
                                        <div class="event-text">
                                            <h3><a href="#">{{event.title}}</a></h3>
                                            <div class="event-time-and-place">
                                                <span class="ev-time"> <i class="fa fa-clock-o" aria-hidden="true"></i> {{event.date}}</span>
                                                <span class="ev-place"> <i class="fa fa-map-marker" aria-hidden="true"></i> {{event.venue}}</span>
                                            </div>
                                            <p>{{event.description}}</p>
                                            <a class="btn-md bo-ra-5" href="{% url 'orgapp:eventdetail' event.pk %}">Read More</a>
                                        </div>
                                    </div>
                                </div>

                                <!-- End single event -->
                            </div>
                         
                        </div>
                          {% endfor %}
                    </div>
                </div>
            </section>
            








{% endblock %}

templates/clienttemplates/home.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block home %}active{% endblock %}

{% block content %}

<!-- Start slider area -->
        	<section class="slider-area">
        		<!-- start enable -->
				<div class="ma-banner7-container">
		        	<div class="container-slider">
			        	<div class="flexslider ma-nivoslider">
		        			<div class="ma-loading"></div>
							<div id="ma-inivoslider-banner7" class="slides">
					        	{% for slider in sliders %}


								<img  src="{{slider.image.url}}" style="height: 300px" alt="" title="#banner7-caption{{forloop.counter}}"/>
								{% endfor %}
							</div>

			        	{% for slider in sliders %}
							<div id="banner7-caption{{forloop.counter}}" class="banner7-caption nivo-html-caption nivo-caption">
								<div class="timethai" style=" 
									position:absolute;
									bottom:0;
									left:0;
									background-color: rgba(255, 255, 255, 0.6);
									height:5px;
									-Charitykit-animation: myfirst 5000ms ease-in-out;
									-moz-animation: myfirst 5000ms ease-in-out;
									-ms-animation: myfirst 5000ms ease-in-out;
									animation: myfirst 5000ms ease-in-out;
								   ">
							    </div>
								<div class="banner7-content slider-1 hidden-xs">
									<h1 class="title1 wow slideInRight" data-wow-duration="1s" data-wow-delay="300ms">{{slider.title}}</h1>
									<p class="wow slideInRight" data-wow-duration="1s" data-wow-delay="600ms">{{slider.caption}}</p>
								</div>
							</div>

					{% endfor %}
						</div>
		    		</div>
				</div>
		    	<!-- end enable -->
        	</section>
        	<!-- End slider area -->


  <section class="about-content-area pt-90 pb-60">
                <div class="container">
                    <div class="row">

                        <div class="col-sm-6">
                            <div class="about-content">
                                <!-- Start section title -->
                                <div class="section-title text-center">
                                    <h2>About <span>Us</span></h2>
                                    <img src="img/title-bottom.png" alt="">
                                </div>
                                <!-- End section title -->
                                <p>{{org.about_us|striptags|truncatechars:300|safe}}</p>
                                <div class="about-button btn-lg-f bo-ra-3">
                                    <a href="{% url 'orgapp:about' %}">Read More</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="about-image">
                                <img src="{{org.profile_image.url}}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </section>








            <!-- Start blog area -->
            <section class="blog-area pt-90 pb-90">
                <div class="container">
                    <div class="row">
                        <!-- Start section title -->
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>LATEST  <a href="{% url 'orgapp:eventlist' %}"><span>Event</span></a></h2>
                                <img src="img/title-bottom.png" alt="">
                            </div>
                        </div>
                        <!-- End section title -->
                        <!-- Start blog -->
                        <div class="row">
                      {% for event in events|slice:3 %}
                        <div class="col-sm-12">
                            <div class="up-comming-events">
                                <!-- Start single event -->
                                <div class="single-event mb-90 row">
                                    <div class="col-sm-5">
                                        <div class="event-image">
                                           <a href="{% url 'orgapp:eventdetail' event.pk %}"> <img src="{{event.image.url}}" alt=""></a>
                                    
                                        </div>
                                    </div>
                                    <div class="col-sm-7">
                                        <div class="event-text">
                                            <h3><a href="{% url 'orgapp:eventdetail' event.pk %}">{{event.title}}</a></h3>
                                            <div class="event-time-and-place">
                                                <span class="ev-time"> <i class="fa fa-clock-o" aria-hidden="true"></i> {{event.date}}</span>
                                                <span class="ev-place"> <i class="fa fa-map-marker" aria-hidden="true"></i> {{event.venue}}</span>
                                            </div>
                                            <p>{{event.description}}</p>
                                            <a class="btn-md bo-ra-5" href="{% url 'orgapp:eventdetail' event.pk %}">Read More</a>
                                        </div>
                                    </div>
                                </div>

                                <!-- End single event -->
                            </div>
                          
                        </div>
                          {% endfor %}
                    </div>
                        <div>
                           <a href="{% url 'orgapp:eventlist' %}"> <button class="btn btn-block">More Events</button></a>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End blog area -->







            <section class="our-volunteers-area pt-90 pb-90">
                <div class="container">
                    <div class="row">
                        <!-- Start section title -->
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>OUR <a href="{% url 'orgapp:memberlist' %}"><span>Members</span></a></h2>
                                <img src="img/title-bottom.png" alt="">
                            </div>
                        </div>
                        <!-- End section title -->
                        	{% for member in members|slice:4 %}
                        <div class="our-volunteers">
                            <div class="col-sm-3">
                                <div class="single-volunteer">
                                    <div class="volunteer-image-and-social">
                                       <a href="{% url 'orgapp:memberlist' %}"><img src="{{member.image.url}}" alt="" style="height: 300px; object-fit: cover;"></a> 
                                    </div>
                                    <div class="volunteer-title text-center">
                                        <h5>{{member.name}}</h5>
                                       <!--  <p>{{member.post}}</p> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                            {% endfor %}   

                    </div>
                    <br>
                    <br>
                    <br>
                     <div>
                    
                           <a href="{% url 'orgapp:memberlist' %}"> <button class="btn btn-block">More Members</button></a>
                        </div>
                   

                </div>

                    
            

            </section>




            <section class="our-gallery pt-90 pb-60">
                <div class="container">
                    <div class="row">
                        <!-- Start section title -->
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>OUR <a href="{% url 'orgapp:albumlist' %}"><span>Gallery</span></a></h2>
                                <img src="img/title-bottom.png" alt="">
                            </div>
                        </div>
                        <!-- End section title -->
                        <div class="gallery-area">
                          
                            <div id="gallery-filter">
                                <!-- Start single gallery -->
                                {% for album in albums|slice:4 %}
                                <div class="col-sm-3 mb-30 single-gallery mix all Charity Wildlife ">
									<div class="gallery-image-and-text">
										<a class=" text-center" href="{% url 'orgapp:albumdetail' album.id %}">
										<img class="img-responsive" src="{{album.image_set.first.image.url}}" alt=""  style="height: 200px;" />
											<i class="fa fa-plus-square-o" aria-hidden="true"></i>
											<p>{{album.title}}</p>
										</a>
									</div>
                                </div>

							{% endfor %}

                            </div>
                             <div>
                    
                           <a href="{% url 'orgapp:albumlist' %}"> <button class="btn btn-block">More Album</button></a>
                        </div>

                        </div>
                    </div>
                </div>
            </section>







            <!-- Start blog area -->
            <section class="blog-area pt-90 pb-90">
                <div class="container">
                    <div class="row">
                        <!-- Start section title -->
                        <div class="col-sm-12">
                            <div class="section-title text-center">
                                <h2>LATEST FROM <span>Article</span></h2>
                                <img src="img/title-bottom.png" alt="">
                                <p>We create events aiming to spear the voice for children and gather for <br>support Please update with our events</p>
                            </div>
                        </div>
                        <!-- End section title -->
                        <!-- Start blog -->
                        <div class="blog">
                            <!-- Start single blog -->
                            {% for arti in articles|slice:4 %}
                            <div class="col-sm-4">
                                <div class="single-blog">
                                    <div class="blo-image-and-date">
                                        <img src="{{arti.image.url}}" alt="" style="object-fit: contain; height: 200px;">
                                 </div>
                                    <div class="blog-text">
                                        <h3><a href="#">{{arti.title}}</a></h3>
                                        <p>{{arti.content|truncatechars:40}}</p>
                                        <a href="#">Read More...</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <br>
                            <br>
                            <br>
                            <br>

                        </div>
                    </div>
                     <!--  <div>
                               
                    
                           <a href="{% url 'orgapp:albumlist' %}"> <button class="btn btn-block">More Album</button></a>
                        </div> -->

                </div>
            </section>
            <!-- End blog area -->











{% endblock %}