orgapp/urls.py
from django.urls import path
from .views import *


app_name = "orgapp"

urlpatterns = [
    # Admin Urls
    path('signin/', SigninView.as_view(), name="signin"),
    path('signout/', SignoutView.as_view(), name="signout"),
    path('admin/organization/', AdminOrganizationView.as_view(),
         name="adminorganization"),
    path('admin/organization/<int:pk>/edit/',
         AdminOrganizationUpdateView.as_view(), name="adminorganizationupdate"),
    path('admin/member/list/', AdminMemberListView.as_view(), name="adminmemberlist"),
    path('admin/member/create/', AdminMemberCreateView.as_view(),
         name="adminmembercreate"),
    path('admin/member/<int:pk>/edit/',
         AdminMemberUpdateView.as_view(), name="adminmemberupdate"),
    path('admin/member/<int:pk>/delete/',
         AdminMemberDeleteView.as_view(), name="adminmemberdelete"),
    path('admin/slider/list/', AdminSliderListView.as_view(), name='adminsliderlist'),
    path('admin/slider/create/', AdminSliderCreateView.as_view(),
         name='adminslidercreate'),
    path('admin/slider/<int:pk>/edit/',
         AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    path('admin/slider/<int:pk>/delete/',
         AdminSliderDeleteView.as_view(), name='adminsliderdelete'),
    path('admin/publication/list/', AdminPublicationListView.as_view(),
         name='adminpublicationlist'),
    path('admin/publication/create/', AdminPublicationCreateView.as_view(),
         name='adminpublicationcreate'),
    path('admin/publication/<int:pk>/edit/',
         AdminPublicationUpdateView.as_view(), name='adminpublicationupdate'),
    path('admin/publication/<int:pk>/delete/',
         AdminPublicationDeleteView.as_view(), name='adminpublicationdelete'),
    path('admin/contact/list/', AdminContactListView.as_view(),
         name='admincontactlist'),
    path('admin/download/list/', AdminDownloadListView.as_view(),
         name='admindownloadlist'),
    path('admin/download/create/', AdminDownloadCreateView.as_view(),
         name='admindownloadcreate'),
    path('admin/download/<int:pk>/edit/',
         AdminDownloadUpdateView.as_view(), name='admindownloadupdate'),
    path('admin/download/<int:pk>/delete/',
         AdminDownloadDeleteView.as_view(), name='admindownloaddelete'),
    path('admin/album/list/', AdminAlbumListView.as_view(), name='adminalbumlist'),
    path('admin/album/create/', AdminAlbumCreateView.as_view(),
         name='adminalbumcreate'),
    path('admin/album/<int:pk>/edit/',
         AdminAlbumUpdateView.as_view(), name='adminalbumupdate'),
    path('admin/album/<int:pk>/delete/',
         AdminAlbumDeleteView.as_view(), name='adminalbumdelete'),
    path('admin/image/list/', AdminImageListView.as_view(), name='adminimagelist'),
    path('admin/image/create/', AdminImageCreateView.as_view(),
         name='adminimagecreate'),
    path('admin/image/<int:pk>/edit/',
         AdminImageUpdateView.as_view(), name='adminimageupdate'),
    path('admin/image/<int:pk>/delete/',
         AdminImageDeleteView.as_view(), name='adminimagedelete'),
    path('admin/article/list/', AdminArticleListView.as_view(),
         name='adminarticlelist'),
    path('admin/article/create/', AdminArticleCreateView.as_view(),
         name='adminarticlecreate'),
    path('admin/article/<int:pk>/edit/',
         AdminArticleUpdateView.as_view(), name='adminarticleupdate'),
    path('admin/article/<int:pk>/delete/',
         AdminArticleDeleteView.as_view(), name='adminarticledelete'),
    path('admin/event/list/', AdminEventListView.as_view(), name='admineventlist'),
    path('admin/event/create/', AdminEventCreateView.as_view(),
         name='admineventcreate'),
    path('admin/event/<int:pk>/edit/',
         AdminEventUpdateView.as_view(), name='admineventupdate'),
    path('admin/event/<int:pk>/delete/',
         AdminEventDeleteView.as_view(), name='admineventdelete'),
    path('admin/password/change', AdminPasswordChangeView.as_view(), name= "passwordchanged"),










    # client urls
    path('', HomeView.as_view(), name="home"),
    path('about/', AboutView.as_view(), name="about"),
    path('contact/', ContactCreateView.as_view(), name="contact"),
    path('event/list/', EventListView.as_view(), name="eventlist"),
    path('event/<int:pk>/detail/', EventDetailView.as_view(), name="eventdetail"),
    path('album/', AlbumView.as_view(), name="albumlist"),
    path('album/detail/<int:pk>/', AlbumDetailView.as_view(), name="albumdetail"),
    path('member/', MemberView.as_view(), name="memberlist"),
    path('article/', ArticleView.as_view(), name="articlelist"),
    path('article/<int:pk>/detail/',
         ArticleDetailView.as_view(), name="articledetail"),
    path("subscriber/", SubscriberCreateView.as_view(), name="subscriber"),
    path("publication/", PublicationView.as_view(), name="publication"),
    path("publication/<int:pk>/detail/", PublicationDetailView.as_view(), name="publicationdetail"),
    path("download/", DownloadView.as_view(), name="download"),
















]

orgproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('orgapp.urls')),
    path('summernote/', include('django_summernote.urls')),
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/admincontactlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block contact %}active{% endblock %}
{% block content %}

          
   <!-- Tables content -->
            <section class="tables-section">
                <!-- table1 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Message List</h4>
                    <table class="table" id="orginfo">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Mobile</th>
                                <th scope="col">Email</th>
                                <th scope="col">subject</th>
                                <th scope="col">Message</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for publ in messagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{publ.name}}</td>
                                <td>{{publ.mobile}}</td>
                                <td>{{publ.email}}</td>
                                <td>{{publ.subject}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter{{forloop.counter}}">
                                      View
                                    </button>
                            
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModalCenter{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                      <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Message</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                            </button>
                                          </div>
                                          <div class="modal-body">
                                            {{publ.message}}
                                          </div>
                                       <!--    <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="button" class="btn btn-primary">Save changes</button>
                                          </div> -->
                                        </div>
                                      </div>
                                    </div>
                                     
                                    
                                 
                                </td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% block js %}
               <script type="text/javascript">
                $(document).ready(function() {
                $('#orginfo').DataTable();
                });

                
    </script>
    {% endblock %}





{% endblock %}

templates/admintemplates/admindownloadcreate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

      <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Download Create</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                {{form.title}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Short Detail</label>
                               {{form.short_details}}
                            </div>
                        </div>
                          <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">File</label>
                                {{form.file}}
                              
                            </div>
                        </div>
                       
                      
                      
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>

{% endblock %}

templates/admintemplates/admindownloaddelete.html
{% extends 'admintemplates/adminbase.html' %}


{% block content %}
<h3>Download Delete</h3>
<form method="POST">
	{% csrf_token %}
<p>Are you sure you want to delete?</p>
<button class="btn btn-danger">Yes</button>
<a href="/admin/event/list/" class="btn btn-primary">No</a>

</form>

{% endblock %}

templates/admintemplates/admindownloadlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block download %}active{% endblock %}
{% block content %}

          
   <!-- Tables content -->
            <section class="tables-section">
                <!-- table1 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Download List</h4>
                     <a href="{% url 'orgapp:admindownloadcreate' %}"  style="font-size: 40px;margin-left: 1200px"><span class="fas fa-plus-circle text-primary"></span></a>
                    <table class="table" id="orginfo">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Title</th>
                                <th scope="col">File</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for publ in downloadlist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{publ.title}}</td>
                                <td>{{publ.file}}</td>
                                 <td>
                                    <a href="{% url 'orgapp:admindownloadupdate' publ.pk %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                    <a href="{% url 'orgapp:admindownloaddelete' publ.pk %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% block js %}
               <script type="text/javascript">
                $(document).ready(function() {
                $('#orginfo').DataTable();
                });

    </script>
    {% endblock %}





{% endblock %}

templates/admintemplates/admineventdelete.html
{% extends 'admintemplates/adminbase.html' %}


{% block content %}
<h3>Event Delete</h3>
<form method="POST">
	{% csrf_token %}
<p>Are you sure you want to delete?</p>
<button class="btn btn-danger">Yes</button>
<a href="/admin/event/list/" class="btn btn-primary">No</a>

</form>

{% endblock %}

templates/admintemplates/admineventupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
  <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Event Update</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                {{form.title}}
                              
                            </div>
                             <div class="form-group col-md-6">
                                <label for="inputPassword4">Date</label>
                               {{form.date}}
                            </div>
                        </div>
                            <div class="form-group">
                            <label for="inputAddress2">Image</label>
                            {{form.image}}
                        
                        </div>

                           <div class="form-group">
                            <label for="inputAddress2">Venue</label>
                            {{form.venue}}
                        
                        </div>
                       
                        <div class="form-group">
                            <label for="inputAddress2">Description</label>
                            {{form.description}}
                        
                        </div>
                      
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
{% endblock %}

templates/admintemplates/adminimagecreate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

  <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Image Create</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Album</label>
                                {{form.album}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Image</label>
                               {{form.image}}
                            </div>
                        </div>
                
                      
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>

{% endblock %}

templates/admintemplates/adminimagelist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block image %}active{% endblock %}
{% block content %}

          
   <!-- Tables content -->
            <section class="tables-section">
                <!-- table1 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Image List</h4>
                     <a href="{% url 'orgapp:adminimagecreate' %}"  style="font-size: 40px;margin-left: 1200px"><span class="fas fa-plus-circle text-primary"></span></a>
                    <table class="table" id="orginfo">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Album</th>
                                <th scope="col">Image</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for publ in imagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{publ.album}}</td>
                                <td><img src="{{publ.image.url}}" width="50px"></td>
                                 <td>
                                    <a href="{% url 'orgapp:adminimageupdate' publ.pk %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                    <a href="{% url 'orgapp:adminimagedelete' publ.pk %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% block js %}
               <script type="text/javascript">
                $(document).ready(function() {
                $('#orginfo').DataTable();
                });

    </script>
    {% endblock %}





{% endblock %}

templates/admintemplates/adminimageupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

  <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Image Update</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputEmail4">Album</label>
                                {{form.album}}
                              
                            </div>
                        </div>
                            <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputPassword4">Image</label>
                               {{form.image}}
                            </div>
                        </div>
                
                      
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>

{% endblock %}

templates/admintemplates/adminlogin.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Modernize an Admin Panel Category Bootstrap Responsive Web Template | Login :: w3layouts</title>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Modernize Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //Meta Tags -->

    <!-- Style-sheets -->
    <!-- Bootstrap Css -->
    <link href="{% static 'adminstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- Bootstrap Css -->
    <!-- Common Css -->
    <link href="{% static 'adminstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!--// Common Css -->
    <!-- Fontawesome Css -->
    <link href="{% static 'adminstatic/css/fontawesome-all.css' %}" rel="stylesheet">
    <!--// Fontawesome Css -->
    <!--// Style-sheets -->

    <!--web-fonts-->
    <link href="//fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!--//web-fonts-->
</head>

<body>
    <div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>
            <!--// main-heading -->
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                <form action="#" method="post">
                    {% if error %}
                    <li class="text-danger">{{error}}</li>
                    
                     {% endif %}


                    {% csrf_token %}
                    <div class="form-group">
                        <label>Email address</label>
                      {{form.username}}
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                     {{form.password}}
                    </div>

                    <button type="submit" class="btn btn-primary error-w3l-btn mt-sm-5 mt-3 px-4">Login</button>
                </form>
            </div>

            <!-- Copyright -->
            <div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">
                <p>© 2018 Modernize . All Rights Reserved | Design by
                    <a href="http://w3layouts.com/"> W3layouts </a>
                </p>
            </div>
            <!--// Copyright -->
        </div>
    </div>


    <!-- Required common Js -->
    <script src='js/jquery-2.2.3.min.js'></script>
    <!-- //Required common Js -->

    <!-- Js for bootstrap working-->
    <script src="js/bootstrap.min.js"></script>
    <!-- //Js for bootstrap working -->

</body>

</html>

templates/admintemplates/adminmembercreate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
         <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Member Create</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Name</label>
                                {{form.name}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Member Type</label>
                               {{form.member_type}}
                            </div>
                        </div>
                           <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Post</label>
                                {{form.post}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Image</label>
                               {{form.image}}
                            </div>
                        </div>
                           <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Mobile</label>
                                {{form.mobile}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Email</label>
                               {{form.email}}
                            </div>
                        </div>
                    
                       
                        <div class="form-group">
                            <label for="inputAddress2">About</label>
                            {{form.about}}
                        
                        </div>
                      
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>

                {% endblock %}

templates/admintemplates/adminmemberupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

   <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Member Update</h4>
                    <hr>
                    <form action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="inputEmail4">Name</label>
                                {{form.name}}
                              
                            </div>
                            <div class="form-group col-md-4">
                                <label for="inputPassword4">Member Type</label>
                               {{form.member_type}}
                            </div>
                               <div class="form-group col-md-4">
                                <label for="inputEmail4">Post</label>
                                {{form.post}}
                              
                            </div>
                        </div>
                           <div class="form-row">
                         
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Image</label>
                               {{form.image}}
                            </div>
                        </div>
                           <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Mobile</label>
                                {{form.mobile}}
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Email</label>
                               {{form.email}}
                            </div>
                        </div>
                    
                       
                        <div class="form-group">
                            <label for="inputAddress2">About</label>
                            {{form.about}}
                        
                        </div>
                      
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>



{% endblock %}

templates/admintemplates/passwordchange.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Modernize an Admin Panel Category Bootstrap Responsive Web Template | Login :: w3layouts</title>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Modernize Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //Meta Tags -->

    <!-- Style-sheets -->
    <!-- Bootstrap Css -->
    <link href="{% static 'adminstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- Bootstrap Css -->
    <!-- Common Css -->
    <link href="{% static 'adminstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!--// Common Css -->
    <!-- Fontawesome Css -->
    <link href="{% static 'adminstatic/css/fontawesome-all.css' %}" rel="stylesheet">
    <!--// Fontawesome Css -->
    <!--// Style-sheets -->

    <!--web-fonts-->
    <link href="//fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!--//web-fonts-->
</head>

<body>
    <div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>
            <!--// main-heading -->
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                <form action="#" method="post">
                    {% if error %}
                    <li class="text-danger">{{error}}</li>
                    
                     {% endif %}


                    {% csrf_token %}
                    <div class="form-group">
                        <label>Username</label>
                      <input type="text" name="" value="{{request.user}} " class="form-control" disabled>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        {{form.password}}
                    </div>

                    <div class="form-group">
                        <label>Change Password</label>
                        {{form.changepassword}}
                    </div>


              
                    <button type="submit" class="btn btn-primary error-w3l-btn mt-sm-5 mt-3 px-4">Login</button>
                </form>
           
            </div>

            <!-- Copyright -->
            <div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">
                <p>© 2018 Modernize . All Rights Reserved | Design by
                    <a href="http://w3layouts.com/"> W3layouts </a>
                </p>
            </div>
            <!--// Copyright -->
        </div>
    </div>


    <!-- Required common Js -->
    <script src='js/jquery-2.2.3.min.js'></script>
    <!-- //Required common Js -->

    <!-- Js for bootstrap working-->
    <script src="js/bootstrap.min.js"></script>
    <!-- //Js for bootstrap working -->

</body>

</html>